// <auto-generated />
using System;
using ElectCrm.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectCrm.Infrastructure.Migrations
{
    [DbContext(typeof(ElectCrmDbContext))]
    [Migration("20260526155106_AddWorkerOnboardingSlice")]
    partial class AddWorkerOnboardingSlice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElectCrm.Domain.AgencyBrands.AgencyBrand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentPersonaName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompaniesHouseNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DwpAccountId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GlaaLicenceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OnCallContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeOnly?>("OnCallQuietHoursEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("OnCallQuietHoursStart")
                        .HasColumnType("time");

                    b.Property<DateTimeOffset>("OnboardedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PrimaryContactEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TradingName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CompaniesHouseNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("AgencyBrands", (string)null);
                });

            modelBuilder.Entity("ElectCrm.Domain.Branches.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgencyBrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Geography")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AgencyBrandId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Branches_AgencyBrandId_Name");

                    b.HasIndex("AgencyBrandId", "Status");

                    b.ToTable("Branches", (string)null);
                });

            modelBuilder.Entity("ElectCrm.Domain.Candidates.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgencyBrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("OwnerConsultantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PrimaryTrade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceLegacyId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AgencyBrandId")
                        .HasDatabaseName("IX_Candidates_AgencyBrandId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Candidates_IsDeleted");

                    b.HasIndex("OwnerConsultantId")
                        .HasDatabaseName("IX_Candidates_OwnerConsultantId");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("IX_Candidates_PersonId");

                    b.HasIndex("RegistrationDate")
                        .HasDatabaseName("IX_Candidates_RegistrationDate");

                    b.HasIndex("AgencyBrandId", "Status")
                        .HasDatabaseName("IX_Candidates_AgencyBrandId_Status");

                    b.HasIndex("PersonId", "AgencyBrandId")
                        .IsUnique()
                        .HasDatabaseName("IX_Candidates_PersonId_AgencyBrandId")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Candidates", (string)null);
                });

            modelBuilder.Entity("ElectCrm.Domain.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgencyBrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PrimaryBranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TradingName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AgencyBrandId")
                        .HasDatabaseName("IX_Clients_AgencyBrandId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Clients_IsDeleted");

                    b.HasIndex("PrimaryBranchId")
                        .HasDatabaseName("IX_Clients_PrimaryBranchId");

                    b.HasIndex("AgencyBrandId", "Status")
                        .HasDatabaseName("IX_Clients_AgencyBrandId_Status");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("ElectCrm.Domain.Compliance.ComplianceDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DocumentReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date");

                    b.Property<Guid>("LastModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OtherDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpiryDate")
                        .HasDatabaseName("IX_ComplianceDocuments_ExpiryDate");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("IX_ComplianceDocuments_PersonId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ComplianceDocuments_Status");

                    b.HasIndex("VerifiedByUserId");

                    b.HasIndex("PersonId", "DocumentType")
                        .HasDatabaseName("IX_ComplianceDocuments_PersonId_DocumentType");

                    b.ToTable("ComplianceDocuments", (string)null);
                });

            modelBuilder.Entity("ElectCrm.Domain.Contacts.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgencyBrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PrimaryForCategories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AgencyBrandId");

                    b.HasIndex("ClientId");

                    b.HasIndex("AgencyBrandId", "ClientId");

                    b.HasIndex("AgencyBrandId", "Status");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("ElectCrm.Domain.Persons.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("ErasedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FullNameNormalised")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NationalInsuranceNumberEncrypted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalInsuranceNumberHash")
                        .HasColumnType("nchar(64)");

                    b.Property<string>("PassportNumberEncrypted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNumberHash")
                        .HasColumnType("nchar(64)");

                    b.Property<string>("PrimaryPhoneEncrypted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryPhoneHash")
                        .HasColumnType("nchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("NationalInsuranceNumberHash");

                    b.HasIndex("PassportNumberHash");

                    b.HasIndex("PrimaryPhoneHash");

                    b.HasIndex("Status");

                    b.HasIndex("FullNameNormalised", "DateOfBirth");

                    b.ToTable("Persons", (string)null);
                });

            modelBuilder.Entity("ElectCrm.Domain.Placements.Placement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("ActualEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ActualStartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("AgencyBrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BillRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConsultantOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly?>("ExpectedEndDate")
                        .HasColumnType("date");

                    b.Property<decimal>("HoursPerWeek")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateOnly>("ProposedStartDate")
                        .HasColumnType("date");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("SnapshotBillRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("SnapshotTakenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgencyBrandId")
                        .HasDatabaseName("IX_Placements_AgencyBrandId");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("IX_Placements_CandidateId");

                    b.HasIndex("ConsultantOwnerId")
                        .HasDatabaseName("IX_Placements_ConsultantOwnerId");

                    b.HasIndex("VacancyId")
                        .HasDatabaseName("IX_Placements_VacancyId");

                    b.HasIndex("AgencyBrandId", "ReferenceNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Placements_AgencyBrandId_ReferenceNumber");

                    b.HasIndex("AgencyBrandId", "Status")
                        .HasDatabaseName("IX_Placements_AgencyBrandId_Status");

                    b.HasIndex("CandidateId", "Status")
                        .HasDatabaseName("IX_Placements_CandidateId_Status");

                    b.HasIndex("VacancyId", "Status")
                        .HasDatabaseName("IX_Placements_VacancyId_Status");

                    b.HasIndex("AgencyBrandId", "Status", "ProposedStartDate")
                        .HasDatabaseName("IX_Placements_AgencyBrandId_Status_ProposedStartDate");

                    b.ToTable("Placements", (string)null);
                });

            modelBuilder.Entity("ElectCrm.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgencyBrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("LastActiveAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AgencyBrandId");

                    b.HasIndex("BranchId");

                    b.HasIndex("AgencyBrandId", "Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ElectCrm.Domain.Users.UserInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("AgencyBrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InvitedEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("Token")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("AgencyBrandId", "InvitedEmail");

                    b.HasIndex("AgencyBrandId", "Status");

                    b.ToTable("UserInvites", (string)null);
                });

            modelBuilder.Entity("ElectCrm.Domain.Vacancies.Vacancy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgencyBrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BillRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConsultantOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedFrom")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ExpectedEndDate")
                        .HasColumnType("date");

                    b.Property<int>("HeadcountRequired")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RequiredCards")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ShiftPattern")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AgencyBrandId")
                        .HasDatabaseName("IX_Vacancies_AgencyBrandId");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("IX_Vacancies_BranchId");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("IX_Vacancies_ClientId");

                    b.HasIndex("ConsultantOwnerId")
                        .HasDatabaseName("IX_Vacancies_ConsultantOwnerId");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("IX_Vacancies_StartDate");

                    b.HasIndex("AgencyBrandId", "ReferenceNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Vacancies_AgencyBrandId_ReferenceNumber");

                    b.HasIndex("AgencyBrandId", "Status")
                        .HasDatabaseName("IX_Vacancies_AgencyBrandId_Status");

                    b.ToTable("Vacancies", (string)null);
                });

            modelBuilder.Entity("ElectCrm.Domain.Workers.WorkerInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgencyBrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ConsumedByPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedByConsultantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExistingPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PrefillEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PrefillFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrefillLastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrefillPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumedByPersonId");

                    b.HasIndex("CreatedByConsultantId")
                        .HasDatabaseName("IX_WorkerInvites_CreatedByConsultantId");

                    b.HasIndex("ExistingPersonId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_WorkerInvites_ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkerInvites_Token");

                    b.HasIndex("AgencyBrandId", "Status")
                        .HasDatabaseName("IX_WorkerInvites_AgencyBrandId_Status");

                    b.ToTable("WorkerInvites", (string)null);
                });

            modelBuilder.Entity("ElectCrm.Domain.Workers.WorkerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NationalInsuranceNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("RightToWorkDeclaredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkerProfiles_ApplicationUserId");

                    b.ToTable("WorkerProfiles", (string)null);
                });

            modelBuilder.Entity("ElectCrm.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("ElectCrm.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("");

                    b.Property<Guid>("DomainUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PrimaryBranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RequirePasswordChange")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DomainUserId")
                        .IsUnique();

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_AspNetUsers_IsActive");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PrimaryBranchId")
                        .HasDatabaseName("IX_AspNetUsers_PrimaryBranchId");

                    b.HasIndex("PrimaryBranchId", "IsActive")
                        .HasDatabaseName("IX_AspNetUsers_PrimaryBranchId_IsActive");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ElectCrm.Domain.AgencyBrands.AgencyBrand", b =>
                {
                    b.OwnsOne("ElectCrm.Domain.Common.ValueObjects.Address", "RegisteredAddress", b1 =>
                        {
                            b1.Property<Guid>("AgencyBrandId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("RegisteredAddressCity");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("RegisteredAddressCountry");

                            b1.Property<string>("County")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("RegisteredAddressCounty");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("RegisteredAddressLine1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("RegisteredAddressLine2");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("RegisteredAddressPostcode");

                            b1.HasKey("AgencyBrandId");

                            b1.ToTable("AgencyBrands");

                            b1.WithOwner()
                                .HasForeignKey("AgencyBrandId");
                        });

                    b.Navigation("RegisteredAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("ElectCrm.Domain.Branches.Branch", b =>
                {
                    b.HasOne("ElectCrm.Domain.AgencyBrands.AgencyBrand", null)
                        .WithMany()
                        .HasForeignKey("AgencyBrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ElectCrm.Domain.Common.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("BranchId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AddressCity");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("AddressCountry");

                            b1.Property<string>("County")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AddressCounty");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("AddressLine1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("AddressLine2");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("AddressPostcode");

                            b1.HasKey("BranchId");

                            b1.ToTable("Branches");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("ElectCrm.Domain.Candidates.Candidate", b =>
                {
                    b.HasOne("ElectCrm.Domain.AgencyBrands.AgencyBrand", null)
                        .WithMany()
                        .HasForeignKey("AgencyBrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElectCrm.Domain.Users.User", "OwnerConsultant")
                        .WithMany()
                        .HasForeignKey("OwnerConsultantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ElectCrm.Domain.Persons.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerConsultant");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ElectCrm.Domain.Clients.Client", b =>
                {
                    b.HasOne("ElectCrm.Domain.AgencyBrands.AgencyBrand", null)
                        .WithMany()
                        .HasForeignKey("AgencyBrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElectCrm.Domain.Branches.Branch", "PrimaryBranch")
                        .WithMany()
                        .HasForeignKey("PrimaryBranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PrimaryBranch");
                });

            modelBuilder.Entity("ElectCrm.Domain.Compliance.ComplianceDocument", b =>
                {
                    b.HasOne("ElectCrm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElectCrm.Domain.Persons.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElectCrm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("VerifiedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("ElectCrm.Domain.Contacts.Contact", b =>
                {
                    b.HasOne("ElectCrm.Domain.AgencyBrands.AgencyBrand", null)
                        .WithMany()
                        .HasForeignKey("AgencyBrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ElectCrm.Domain.Contacts.ChannelPrefs", "CommunicationPreferences", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Channel")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("ChannelPrefs_Channel");

                            b1.Property<string>("PreferredDays")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("ChannelPrefs_PreferredDays");

                            b1.Property<TimeOnly?>("QuietHoursEnd")
                                .HasColumnType("time")
                                .HasColumnName("ChannelPrefs_QuietHoursEnd");

                            b1.Property<TimeOnly?>("QuietHoursStart")
                                .HasColumnType("time")
                                .HasColumnName("ChannelPrefs_QuietHoursStart");

                            b1.HasKey("ContactId");

                            b1.ToTable("Contacts");

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.Navigation("CommunicationPreferences");
                });

            modelBuilder.Entity("ElectCrm.Domain.Placements.Placement", b =>
                {
                    b.HasOne("ElectCrm.Domain.AgencyBrands.AgencyBrand", null)
                        .WithMany()
                        .HasForeignKey("AgencyBrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElectCrm.Domain.Candidates.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElectCrm.Domain.Users.User", "ConsultantOwner")
                        .WithMany()
                        .HasForeignKey("ConsultantOwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ElectCrm.Domain.Vacancies.Vacancy", "Vacancy")
                        .WithMany()
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ElectCrm.Domain.Placements.PlacementPayRate", "PayRate", b1 =>
                        {
                            b1.Property<Guid>("PlacementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("PayRate_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("PayRate_Currency");

                            b1.Property<string>("EngagementType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("PayRate_EngagementType");

                            b1.Property<bool>("HolidayPayInclusive")
                                .HasColumnType("bit")
                                .HasColumnName("PayRate_HolidayPayInclusive");

                            b1.Property<decimal?>("HolidayPayRate")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("PayRate_HolidayPayRate");

                            b1.HasKey("PlacementId");

                            b1.ToTable("Placements");

                            b1.WithOwner()
                                .HasForeignKey("PlacementId");
                        });

                    b.OwnsOne("ElectCrm.Domain.Placements.PlacementPayRate", "SnapshotSourceVacancyPayRate", b1 =>
                        {
                            b1.Property<Guid>("PlacementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("Snapshot_PayRate_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Snapshot_PayRate_Currency");

                            b1.Property<string>("EngagementType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Snapshot_PayRate_EngagementType");

                            b1.Property<bool>("HolidayPayInclusive")
                                .HasColumnType("bit")
                                .HasColumnName("Snapshot_PayRate_HolidayPayInclusive");

                            b1.Property<decimal?>("HolidayPayRate")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("Snapshot_PayRate_HolidayPayRate");

                            b1.HasKey("PlacementId");

                            b1.ToTable("Placements");

                            b1.WithOwner()
                                .HasForeignKey("PlacementId");
                        });

                    b.Navigation("Candidate");

                    b.Navigation("ConsultantOwner");

                    b.Navigation("PayRate")
                        .IsRequired();

                    b.Navigation("SnapshotSourceVacancyPayRate")
                        .IsRequired();

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("ElectCrm.Domain.Users.User", b =>
                {
                    b.HasOne("ElectCrm.Domain.AgencyBrands.AgencyBrand", null)
                        .WithMany()
                        .HasForeignKey("AgencyBrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElectCrm.Domain.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("ElectCrm.Domain.Users.UserInvite", b =>
                {
                    b.HasOne("ElectCrm.Domain.AgencyBrands.AgencyBrand", null)
                        .WithMany()
                        .HasForeignKey("AgencyBrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ElectCrm.Domain.Vacancies.Vacancy", b =>
                {
                    b.HasOne("ElectCrm.Domain.AgencyBrands.AgencyBrand", null)
                        .WithMany()
                        .HasForeignKey("AgencyBrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElectCrm.Domain.Branches.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElectCrm.Domain.Clients.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElectCrm.Domain.Users.User", "ConsultantOwner")
                        .WithMany()
                        .HasForeignKey("ConsultantOwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("ElectCrm.Domain.Vacancies.PayRate", "PayRate", b1 =>
                        {
                            b1.Property<Guid>("VacancyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("PayRate_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("PayRate_Currency");

                            b1.Property<string>("EngagementType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("PayRate_EngagementType");

                            b1.Property<bool>("HolidayPayInclusive")
                                .HasColumnType("bit")
                                .HasColumnName("PayRate_HolidayPayInclusive");

                            b1.Property<decimal?>("HolidayPayRate")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("PayRate_HolidayPayRate");

                            b1.HasKey("VacancyId");

                            b1.ToTable("Vacancies");

                            b1.WithOwner()
                                .HasForeignKey("VacancyId");
                        });

                    b.OwnsOne("ElectCrm.Domain.Vacancies.VacancyLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("VacancyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Description")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("LocationDescription");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("LocationPostcode");

                            b1.HasKey("VacancyId");

                            b1.ToTable("Vacancies");

                            b1.WithOwner()
                                .HasForeignKey("VacancyId");
                        });

                    b.Navigation("Branch");

                    b.Navigation("Client");

                    b.Navigation("ConsultantOwner");

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("PayRate")
                        .IsRequired();
                });

            modelBuilder.Entity("ElectCrm.Domain.Workers.WorkerInvite", b =>
                {
                    b.HasOne("ElectCrm.Domain.AgencyBrands.AgencyBrand", null)
                        .WithMany()
                        .HasForeignKey("AgencyBrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElectCrm.Domain.Persons.Person", null)
                        .WithMany()
                        .HasForeignKey("ConsumedByPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ElectCrm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByConsultantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ElectCrm.Domain.Persons.Person", null)
                        .WithMany()
                        .HasForeignKey("ExistingPersonId");
                });

            modelBuilder.Entity("ElectCrm.Domain.Workers.WorkerProfile", b =>
                {
                    b.HasOne("ElectCrm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ElectCrm.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.HasOne("ElectCrm.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("ElectCrm.Infrastructure.Identity.ApplicationUser", "DomainUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElectCrm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("LastModifiedById");

                    b.HasOne("ElectCrm.Domain.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("PrimaryBranchId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("ElectCrm.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ElectCrm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ElectCrm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("ElectCrm.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectCrm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ElectCrm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
